package com.hushtv.tv.data

/**
 * Auto-generated by /tmp/build_bundle.py — DO NOT edit by hand.
 *
 * Maps every external CDN URL referenced by static data
 * (streaming services, decade backdrops, theme backdrops,
 * preferred-genre-movie backdrops) to a `file:///android_asset/`
 * path that ships inside the APK.
 *
 * The Coil ImageLoader.Mapper installed in HushTVApp consults
 * this table on every load. A hit means the image paints from
 * APK assets in ~5 ms instead of 500-800 ms via TMDB CDN.
 *
 * Bundle size: 3.09 MB across 44 assets.
 */
object BundledAssets {
    private const val ASSET_PREFIX = "file:///android_asset/"

    /** Source-URL → asset relative path. */
    private val MAP: Map<String, String> = mapOf(
        "https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/united-states/amc-us.png" to "bundled/streaming/amc.webp",
        "https://clipart-library.com/new_gallery/456504_apple-tv-logo-png.png" to "bundled/streaming/appletv.webp",
        "https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/canada/crave-1-ca.png" to "bundled/streaming/crave.webp",
        "https://github.com/tv-logo/tv-logos/blob/main/countries/united-states/disney-plus-us.png?raw=true" to "bundled/streaming/disney.webp",
        "https://static.vecteezy.com/system/resources/previews/017/396/804/non_2x/netflix-mobile-application-logo-free-png.png" to "bundled/streaming/netflix.webp",
        "https://github.com/tv-logo/tv-logos/blob/main/countries/france/paramount-channel-fr.png?raw=true" to "bundled/streaming/paramount.webp",
        "https://static.vecteezy.com/system/resources/thumbnails/019/766/188/small/prime-video-logo-prime-video-icon-transparent-logo-free-png.png" to "bundled/streaming/prime.webp",
        "https://image.tmdb.org/t/p/original/1ZKHzSGJm0kvlCp4echAOtKnDTm.jpg" to "bundled/decade/1940s.webp",
        "https://image.tmdb.org/t/p/original/stiGp1XzkLSYdUUEWTyQOZRkr49.jpg" to "bundled/decade/1950s.webp",
        "https://image.tmdb.org/t/p/original/e3hG3uadtcP0pYdRa5ch4ysQW76.jpg" to "bundled/decade/1960s.webp",
        "https://image.tmdb.org/t/p/original/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg" to "bundled/decade/1970s.webp",
        "https://image.tmdb.org/t/p/original/mFDQ8f2lPHorGwtuE0fjnUIbKLF.jpg" to "bundled/decade/1980s.webp",
        "https://image.tmdb.org/t/p/original/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg" to "bundled/decade/1990s.webp",
        "https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg" to "bundled/decade/2000s.webp",
        "https://image.tmdb.org/t/p/original/2ssWTSVklAEc98frZUQhgtGHx7s.jpg" to "bundled/decade/2010s.webp",
        "https://image.tmdb.org/t/p/original/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg" to "bundled/decade/2020s.webp",
        "https://image.tmdb.org/t/p/original/qBChUbS8ksbJoPTfZpogsnxG5tY.jpg" to "bundled/theme/true_stories_v1.webp",
        "https://image.tmdb.org/t/p/original/c6OLXfKAk5BKeR6broC8pYiCquX.jpg" to "bundled/theme/plot_twists_v1.webp",
        "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg" to "bundled/theme/mind_bending_v1.webp",
        "https://image.tmdb.org/t/p/original/n1ItmvzsDV5yLgDodSCLZpFlsP6.jpg" to "bundled/theme/hidden_gems_v1.webp",
        "https://image.tmdb.org/t/p/original/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg" to "bundled/theme/make_you_cry_v1.webp",
        "https://image.tmdb.org/t/p/original/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg" to "bundled/theme/feel_good_v1.webp",
        "https://image.tmdb.org/t/p/original/jwBiY1kE5089i2WpfS1MHDYp3VO.jpg" to "bundled/theme/coming_of_age_v1.webp",
        "https://image.tmdb.org/t/p/original/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg" to "bundled/theme/revenge_v1.webp",
        "https://image.tmdb.org/t/p/original/mNQtUJv1F3u0uSKILFrGjIHqkxx.jpg" to "bundled/theme/survival_v1.webp",
        "https://image.tmdb.org/t/p/original/2ssWTSVklAEc98frZUQhgtGHx7s.jpg" to "bundled/theme/time_bending_v1.webp",
        "https://image.tmdb.org/t/p/original/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg" to "bundled/theme/action_comedy_v1.webp",
        "https://image.tmdb.org/t/p/original/dtGxDOcFssdUUTYBr6M6INXTI1e.jpg" to "bundled/theme/dark_comedy_v1.webp",
        "https://image.tmdb.org/t/p/original/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg" to "bundled/theme/psychological_thriller_v1.webp",
        "https://image.tmdb.org/t/p/original/a0lfia8tk8ifkrve0Tn8wkISUvs.jpg" to "bundled/theme/epic_fantasy_v1.webp",
        "https://image.tmdb.org/t/p/original/gILte6Zd7m1YneIr6MVhh30S9pr.jpg" to "bundled/theme/crime_masterpieces_v1.webp",
        "https://image.tmdb.org/t/p/original/iymDDg4upZWgpbSeiE1JCjsSPBs.jpg" to "bundled/theme/late_night_v1.webp",
        "https://image.tmdb.org/t/p/original/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg" to "bundled/theme/watch_with_friends_v1.webp",
        "https://image.tmdb.org/t/p/original/uT895WNwm0aIJRtGizcQhrejWUo.jpg" to "bundled/theme/brain_off_v1.webp",
        "https://image.tmdb.org/t/p/original/askFH4GSk2u9z3ZE5ypdKIMeqLJ.jpg" to "bundled/theme/visually_stunning_v1.webp",
        "https://image.tmdb.org/t/p/original/yir5430WblZSZuIMd9C6pIZerfA.jpg" to "bundled/theme/soundtrack_driven_v1.webp",
        "https://image.tmdb.org/t/p/original/7BYtnXUfweV6EryNYDpZFeS31Ia.jpg" to "bundled/theme/rewatch_decoder_v1.webp",
        "https://image.tmdb.org/t/p/original/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg" to "bundled/theme/better_than_book_v1.webp",
        "https://image.tmdb.org/t/p/original/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg" to "bundled/theme/one_location_v1.webp",
        "https://image.tmdb.org/t/p/original/nHRUtBwFNnNN70vcQ7lAsjc2T6S.jpg" to "bundled/theme/minimal_dialogue_v1.webp",
        "https://image.tmdb.org/t/p/original/sYLzRuEcwSz0L1Z92wQNrETHU9O.jpg" to "bundled/theme/wtf_v1.webp",
        "https://image.tmdb.org/t/p/original/cz4vLJrmaV1zJlRYbxqtvLzeLWB.jpg" to "bundled/genre_movie/28.webp",
        "https://image.tmdb.org/t/p/original/jzt9HuhIAdH9qp0K2MA1m5V8sgq.jpg" to "bundled/genre_movie/12.webp",
        "https://image.tmdb.org/t/p/original/7ar7VuZdK8ihZH2vycXHrhmYUrX.jpg" to "bundled/genre_movie/99001.webp",
    )

    /** Returns the bundled-asset URL for [sourceUrl] or null
     *  if not bundled. The Coil mapper short-circuits to this
     *  when present so the network is never touched. */
    fun resolve(sourceUrl: String): String? {
        val rel = MAP[sourceUrl] ?: return null
        return ASSET_PREFIX + rel
    }

    /** True if the URL has a bundled equivalent. */
    fun has(sourceUrl: String): Boolean = MAP.containsKey(sourceUrl)

    /** Total bundle entries, exposed for telemetry. */
    const val ENTRY_COUNT: Int = 44
}
